# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loade
    
    providers:
        administrators:
            entity: { class: SeguroBundle:Tipousuario, property: tipo }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/nueva/reunion
            anonymous: ~
         

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
      ## - { path: ^/nueva/reunion, roles: ROLE_COBRADOR }
       ##- { path: ^/delete-post, roles: ROLE_USUARIO }


